ALTER TABLE `data`.`T_CM_HOUSE_TANXI`
MODIFY COLUMN `HOUSECODE` VARCHAR ( 50 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '房屋代码' FIRST,
MODIFY COLUMN `BUILDINGUSAGE` VARCHAR ( 2 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '建筑用途' AFTER `HOUSECODE`,
MODIFY COLUMN `AREA` DECIMAL ( 8, 2 ) NULL DEFAULT NULL COMMENT '建筑面积(平方米)' AFTER `BUILDINGUSAGE`,
MODIFY COLUMN `CERTIFICATETYPE` VARCHAR ( 3 ) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '证件代码' AFTER `AREA`,
MODIFY COLUMN `CERTIFICATENO` VARCHAR ( 30 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '证件号码' AFTER `CERTIFICATETYPE`,
MODIFY COLUMN `HOUSEHOLDERNAME` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '房主姓名' AFTER `CERTIFICATENO`,
MODIFY COLUMN `HOUSEHOLDERCERTIFICATENO` VARCHAR ( 100 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '房主证件证号' AFTER `HOUSEHOLDERNAME`,
MODIFY COLUMN `HOUSEHOLDERCONTACT` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '房主现居详址' AFTER `HOUSEHOLDERCERTIFICATENO`,
MODIFY COLUMN `HOUSEHOLDERADDRESS` VARCHAR ( 200 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '房主现居详址' AFTER `HOUSEHOLDERCONTACT`,
MODIFY COLUMN `HOUSEUSAGE` VARCHAR ( 2 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '房屋用途' AFTER `HOUSEHOLDERADDRESS`,
MODIFY COLUMN `HIDDENDANGERTYPE` VARCHAR ( 2 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '隐患类型' AFTER `HOUSEUSAGE`,
MODIFY COLUMN `TENANTCERTIFICATENO` VARCHAR ( 18 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '承租人公民身份证号码' AFTER `HIDDENDANGERTYPE`,
MODIFY COLUMN `TENANTNAME` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '承租人姓名' AFTER `TENANTCERTIFICATENO`,
MODIFY COLUMN `TENANTCONTACT` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '承租人联系方式' AFTER `TENANTNAME`,
MODIFY COLUMN `BUILDINGCODE` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '楼栋编码' AFTER `TENANTCONTACT`,
MODIFY COLUMN `UNITNUM` DECIMAL ( 65, 30 ) NOT NULL COMMENT '所属单元' AFTER `BUILDINGCODE`,
MODIFY COLUMN `FLOORNUM` DECIMAL ( 65, 30 ) NOT NULL COMMENT '所属楼层' AFTER `UNITNUM`,
MODIFY COLUMN `HOUSENO` VARCHAR ( 10 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '门牌号' AFTER `FLOORNUM`,
MODIFY COLUMN `BUILDINGUSAGEVALUE` VARCHAR ( 20 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '建筑用途值' AFTER `HOUSENO`,
MODIFY COLUMN `CERTIFICATETYPEVALUE` VARCHAR ( 50 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '证件代码值' AFTER `BUILDINGUSAGEVALUE`,
MODIFY COLUMN `HOUSEUSAGEVALUE` VARCHAR ( 10 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '房屋用途值' AFTER `CERTIFICATETYPEVALUE`,
MODIFY COLUMN `HIDDENDANGERTYPEVALUE` VARCHAR ( 20 ) CHARACTER
SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '隐患类型值' AFTER `HOUSEUSAGEVALUE`,
MODIFY COLUMN `LASTUPDATETIME` DATETIME NULL DEFAULT NULL COMMENT 'LastUpdateTime' AFTER `HIDDENDANGERTYPEVALUE`,
COMMENT = '檀溪街道房屋表（出租屋表）'


MODIFY COLUMN `HOUSEHOLDERNAME` varchar(50)
MODIFY COLUMN `HOUSEHOLDERCERTIFICATENO` varchar(100)
MODIFY COLUMN `HOUSEHOLDERCONTACT` varchar(50)
MODIFY COLUMN `HOUSEHOLDERADDRESS` varchar(200)
MODIFY COLUMN `HOUSEUSAGE` varchar(2)
MODIFY COLUMN `HIDDENDANGERTYPE` varchar(2)
MODIFY COLUMN `TENANTCERTIFICATENO` varchar(18)
MODIFY COLUMN `TENANTNAME` varchar(50)
MODIFY COLUMN `TENANTCONTACT` varchar(50)
MODIFY COLUMN `BUILDINGCODE` varchar(50)
MODIFY COLUMN `UNITNUM` decimal(65,30)
MODIFY COLUMN `FLOORNUM` decimal(65,30)
MODIFY COLUMN `HOUSENO` varchar(10)
MODIFY COLUMN `BUILDINGUSAGEVALUE` varchar(20)
MODIFY COLUMN `CERTIFICATETYPEVALUE` varchar(50)
MODIFY COLUMN `HOUSEUSAGEVALUE` varchar(10)
MODIFY COLUMN `HIDDENDANGERTYPEVALUE` varchar(20)
MODIFY COLUMN `LASTUPDATETIME` datetime
MODIFY COLUMN `HOUSENUM` varchar(50)
MODIFY COLUMN `CREATETIME` datetime